const MOBILE_VIDEO_WIDTH=320;
const MOBILE_VIDEO_HEIGHT=200;

const TABLET_VIDEO_WIDTH=768;
const TABLET_VIDEO_HEIGHT=400;

const SMALL_DESKTOP_VIDEO_WIDTH=992;
const SMALL_DESKTOP_VIDEO_HEIGHT=600;

const LARGE_DESKTOP_VIDEO_WIDTH=1200;
const LARGE_DESKTOP_VIDEO_HEIGHT=853;
